export const zipCodeMapping ={
    '841243': { country: 'India', city: 'Siwan', state: 'Bihar' },
    '110001': { country: 'India', city: 'New Delhi', state: 'Delhi' },
    '400001': { country: 'India', city: 'Mumbai', state: 'Maharashtra' },
    '560001': { country: 'India', city: 'Bangalore', state: 'Karnataka' },
    '700001': { country: 'India', city: 'Kolkata', state: 'West Bengal' },
    '10001': { country: 'United States', city: 'New York City', state: 'New York' },
    '90001': { country: 'United States', city: 'Los Angeles', state: 'California' },
    '60601': { country: 'United States', city: 'Chicago', state: 'Illinois' },
    '94102': { country: 'United States', city: 'San Francisco', state: 'California' },
    'SW1A 1AA': { country: 'United Kingdom', city: 'London', state: 'England' },
    'M1 1AA': { country: 'United Kingdom', city: 'Manchester', state: 'England' },
    'EH1 1AA': { country: 'United Kingdom', city: 'Edinburgh', state: 'Scotland' },
    'CF10 1AA': { country: 'United Kingdom', city: 'Cardiff', state: 'Wales' },
    'M5H 2N2': { country: 'Canada', city: 'Toronto', state: 'Ontario' },
    'H3B 4G7': { country: 'Canada', city: 'Montreal', state: 'Quebec' },
    'V6C 2R7': { country: 'Canada', city: 'Vancouver', state: 'British Columbia' },
    'T5J 0N3': { country: 'Canada', city: 'Edmonton', state: 'Alberta' },
    '2000': { country: 'Australia', city: 'Sydney', state: 'New South Wales' },
    '3000': { country: 'Australia', city: 'Melbourne', state: 'Victoria' },
    '4000': { country: 'Australia', city: 'Brisbane', state: 'Queensland' },
    '5000': { country: 'Australia', city: 'Adelaide', state: 'South Australia' },
    '00120': { country: 'Finland', city: 'Helsinki', state: 'Uusimaa' },
    '33100': { country: 'Finland', city: 'Tampere', state: 'Pirkanmaa' },
    '150': { country: 'Finland', city: 'Turku', state: 'Varsinais-Suomi' },
    '20100': { country: 'Finland', city: 'Turku', state: 'Varsinais-Suomi' },
    '00150': { country: 'Finland', city: 'Turku', state: 'Varsinais-Suomi' },
    '75002': { country: 'France', city: 'Paris', state: 'Île-de-France' },
    '33000': { country: 'France', city: 'Bordeaux', state: 'Nouvelle-Aquitaine' },
    '69001': { country: 'France', city: 'Lyon', state: 'Auvergne-Rhône-Alpes' },
    '13001': { country: 'France', city: 'Marseille', state: 'Provence-Alpes-Côte d\'Azur' },
    '10178': { country: 'Germany', city: 'Berlin', state: 'Berlin' },
    '60311': { country: 'Germany', city: 'Frankfurt', state: 'Hesse' },
    '20457': { country: 'Germany', city: 'Hamburg', state: 'Hamburg' },
    '80539': { country: 'Germany', city: 'Munich', state: 'Bavaria' },
    '00100': { country: 'Italy', city: 'Rome', state: 'Lazio' },
    '20100': { country: 'Italy', city: 'Milan', state: 'Lombardy' },
    '16121': { country: 'Italy', city: 'Genoa', state: 'Liguria' },
    '34100': { country: 'Italy', city: 'Trieste', state: 'Friuli Venezia Giulia' },
    '841243': { country: 'India', city: 'Siwan', state: 'Bihar' },
    '110001': { country: 'India', city: 'New Delhi', state: 'Delhi' },
    '403004': { country: 'India', city: 'Donna Paula', state: 'Goa' },
    '744204': { country: 'India', city: 'Aberdeen', state: 'Andaman & Nicobar Islands' },
    '799005': { country: 'India', city: 'Abhaynagar', state: 'Tripura' },
    '523201': { country: 'India', city: 'Addanki', state: 'Andhra Pradesh' },
    '504001': { country: 'India', city: 'Adilabad', state: 'Andhra Pradesh' },
    '518301': { country: 'India', city: 'Adoni', state: 'Andhra Pradesh' },
    '691523': { country: 'India', city: 'Adur', state: 'Kerala' },
    '799001': { country: 'India', city: 'Agartala G.P.O', state: 'Tripura' },
    '282003': { country: 'India', city: 'Agra Fort', state: 'Uttar Pradesh' },
    '380001': { country: 'India', city: 'Ahmedabad', state: 'Gujarat' },
    '414001': { country: 'India', city: 'Ahmednagar', state: 'Maharashtra' },
    '796190': { country: 'India', city: 'Aibok', state: 'Mizoram' },
    '796001': { country: 'India', city: 'Aizawal G.P.O', state: 'Mizoram' },
    '305001': { country: 'India', city: 'Ajmer', state: 'Rajasthan' },
    '224122': { country: 'India', city: 'Akbarpur', state: 'Uttar Pradesh' },
    '444001': { country: 'India', city: 'Akola', state: 'Maharashtra' },
    '798619': { country: 'India', city: 'Akulto', state: 'Nagaland' },
    '110005': { country: 'India', city: 'North West Delhi', state: 'Delhi' },
    '110006': { country: 'India', city: 'North Delhi', state: 'Delhi' },
    '110007': { country: 'India', city: 'North Delhi', state: 'Delhi' },
    '110008': { country: 'India', city: 'North Delhi', state: 'Delhi' },
    '110009': { country: 'India', city: 'North Delhi', state: 'Delhi' },
    '282001': { country: 'India', city: 'Agra', state: 'Uttar Pradesh' },
    '110030': { country: 'India', city: 'Mehrauli', state: 'Delhi' },
    '144631': { country: 'India', city: 'Kapurthala', state: 'Punjab' }
}

export const industryOptions = [{ value: 'Auto Components', label: 'Auto Components' },
{ value: 'Automobiles', label: 'Automobiles' },
{ value: 'Aviation', label: 'Aviation' },
{ value: 'Ayush', label: 'Ayush' },
{ value: 'Banking', label: 'Banking' },
{ value: 'Biotechnology', label: 'Biotechnology' },
{ value: 'Cement', label: 'Cement' },
{ value: 'Chemicals', label: 'Chemicals' },
{ value: 'Consumer Durables', label: 'Consumer Durables' },
{ value: 'Defence Manufacturing', label: 'Defence Manufacturing' },
{ value: 'E-Commerce', label: 'E-Commerce' },
{ value: 'Education and Training', label: 'Education and Training' },
{ value: 'Electronics System Design & Manufacturing', label: 'Electronics System Design & Manufacturing' },
{ value: 'Engineering and Capital Goods', label: 'Engineering and Capital Goods' },
{ value: 'Financial Services', label: 'Financial Services' },
{ value: 'FMCG', label: 'FMCG' },
{ value: 'Gems and Jewellery', label: 'Gems and Jewellery' },
{ value: 'Healthcare', label: 'Healthcare' },
{ value: 'Infrastructure', label: 'Infrastructure' },
{ value: 'Insurance', label: 'Insurance' },
{ value: 'IT & BPM', label: 'IT & BPM' },
{ value: 'Manufacturing', label: 'Manufacturing' },
{ value: 'Media and Entertainment', label: 'Media and Entertainment' },
{ value: 'Medical Devices', label: 'Medical Devices' },
{ value: 'Metals and Mining', label: 'Metals and Mining' },
{ value: 'MSME', label: 'MSME' },
{ value: 'Oil and Gas', label: 'Oil and Gas' },
{ value: 'Pharmaceuticals', label: 'Pharmaceuticals' },
{ value: 'Ports', label: 'Ports' },
{ value: 'Power', label: 'Power' },
{ value: 'Railways', label: 'Railways' },
{ value: 'Real Estate', label: 'Real Estate' },
{ value: 'Renewable Energy', label: 'Renewable Energy' },
{ value: 'Retail', label: 'Retail' },
{ value: 'Roads', label: 'Roads' },
{ value: 'Science and Technology', label: 'Science and Technology' },
{ value: 'Services', label: 'Services' },
{ value: 'Steel', label: 'Steel' },
{ value: 'Telecommunications', label: 'Telecommunications' },
{ value: 'Textiles', label: 'Textiles' },
{ value: 'Tourism and Hospitality', label: 'Tourism and Hospitality' }
];
export const branchOptions = [
  { value: 'IT', label: 'IT' },
  { value: 'HR', label: 'HR' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Sales', label: 'Sales' },
  { value: 'Operations', label: 'Operations' },
];

export const departmentOptions = [
  { value: 'Software Development', label: 'Software Development' },
  { value: 'Quality Assurance', label: 'Quality Assurance' },
  { value: 'Data Science', label: 'Data Science' },
  { value: 'Product Management', label: 'Product Management' },
  { value: 'DevOps', label: 'DevOps' },
  { value: 'Customer Support', label: 'Customer Support' },
  { value: 'Accounting', label: 'Accounting' },
  { value: 'Procurement', label: 'Procurement' },
  { value: 'Logistics', label: 'Logistics' },
  { value: 'Supply Chain Management', label: 'Supply Chain Management' },
];

export const positionOptions = [
  { value: 'Software Engineer', label: 'Software Engineer' },
  { value: 'QA Engineer', label: 'QA Engineer' },
  { value: 'Data Scientist', label: 'Data Scientist' },
  { value: 'Product Manager', label: 'Product Manager' },
  { value: 'DevOps Engineer', label: 'DevOps Engineer' },
  { value: 'Customer Support Engineer', label: 'Customer Support Engineer' },
  { value: 'Accountant', label: 'Accountant' },
  { value: 'Procurement Officer', label: 'Procurement Officer' },
  { value: 'Logistics Officer', label: 'Logistics Officer' },
  { value: 'Supply Chain Manager', label: 'Supply Chain Manager' },
];
